service: process-sent-event

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  iam:
    role: arn:aws:iam::742104988707:role/lambda-role

functions:
  processSentEvent:
    handler: handler.processSentEvent
